_wandb:
    value:
        cli_version: 0.21.4
        e:
            kemleizyl48035cnaqw4w1mkqzuybdto:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                args:
                    - --batch-size
                    - "4"
                    - --training-steps
                    - "5000"
                codePath: scripts/train_smolvla_lerobot_v2.py
                codePathLocal: train_smolvla_lerobot_v2.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "233494851584"
                email: kirikoguzhan@gmail.com
                executable: /Users/oguz/miniconda3/envs/lerobot/bin/python
                git:
                    commit: 620f4d106bfca0733a21d5e57342db3bf812e18f
                    remote: https://github.com/OguzhanKirik/ur5_vla.git
                host: MacBookPro
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/oguz/Desktop/workspace_py/ur5_grasp/ur5_grasp/scripts/train_smolvla_lerobot_v2.py
                python: CPython 3.10.19
                root: /Users/oguz/Desktop/workspace_py/ur5_grasp/ur5_grasp/scripts
                startedAt: "2026-01-13T07:11:35.273712Z"
                writerId: kemleizyl48035cnaqw4w1mkqzuybdto
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.21.4
            "6": 4.57.3
            "12": 0.21.4
            "13": darwin-arm64
batch_size:
    value: 4
chunk_size:
    value: 50
dataset:
    value: local/ur5_smolvla_grasp
device:
    value: mps
learning_rate:
    value: 1e-05
pretrained_from:
    value: lerobot/smolvla_base
training_steps:
    value: 5000
